apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 3   # Scale to 3 consumers
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: dasun2020/rabbitproject-consumer:v1
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
